name: Continuos Delivery

on:
  push:
    branches: [main]
    paths: ["**.zig"]

  pull_request:
    branches: [main]
    paths: ["**.zig"]

  workflow_dispatch:

permissions:
  pages: write
  contents: read
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: master

      - name: Run Meduza codebase graph generator
        run: |
          zig env
          zig build meduza -- -r https://github.com/tigerbeetle/tigerbeetle/blob/main/src -l ./tigerbeetle/src -t "Tigerbeetle database" -o ./out/mdz.mmd

      - name: Install Mermaid CLI
        run: |
          curl -so node.tar.xz https://nodejs.org/dist/v18.17.0/node-v18.17.0-linux-x64.tar.xz
          tar xf node.tar.xz
          ./node-v18.17.0-linux-x64/bin/npm install -g @mermaid-js/mermaid-cli

      - name: Emit SVG
        run: |
          echo '{\n    "maxTextSize": 250000\n}' >> config.json
          mmdc -i ./out/mdz.mmd -o ./out/mdz.svg -b black -c config.json

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./out/

  deploy:
    needs: build

    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy artifact to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
