name: Continuos Delivery

on:
  push:
    branches: [main]
    paths: ["**.zig"]

  pull_request:
    branches: [main]
    paths: ["**.zig"]

  workflow_dispatch:

permissions:
  pages: write
  contents: read
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: master

      - name: Run Meduza codebase graph generator
        run: |
          zig env
          zig build meduza -- -r https://github.com/tensorush/zigzag/blob/main/src -l zigzag/src -t "Zigzag path tracer" -o ./out/mdz.mmd

      - name: Install NPM
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false

      - name: Install Mermaid CLI
        run: npm install -g @mermaid-js/mermaid-cli

      - name: Emit SVG
        run: mmdc -i ./out/mdz.mmd -b black

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./out/

  deploy:
    needs: build

    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy artifact to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
